project:
  name: boot-app-gradle
  version: 1.0
  log:
    name: bootAppGradle

server:
  port: 8081

logging:
  config: classpath:logback-spring.xml

logbook:
  exclude:
  - '**/health'
  - '**/v3/api-docs/**'
  - '**/v2/api-docs/**'
  - '**/v1/api-docs/**'
  - '**/swagger-resources/**'
  - '**/configuration/security'
  - '**/swagger'
  - '**/csrf'
  - '**/error'
  - '**/configuration'
  - '**/swagger-ui.html'
  - '**/favicon.*'
  - '**/h2-console/**'
  - '**/webjars/**'
  - '**/swagger-ui/**'
  - '**/swagger-ui/*'
  - '**/swagger-resources/**'
  - '**/etrack/exportArchive'
  - '**/*-stream'
  - '**/admin/**'

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true


---
spring:
  application:
    name: boot-app-gradle
  profiles:
    active: local
  devtools:
    livereload:
      port: 18090
      enabled: true

server:
  port: 8081
#log path
logs:
  absolute:
    path: /Users/mooney/boot-app-gradle
  level:
    root: INFO
    com: DEBUG
  name: bootAppGradle

---
spring:
  application:
    name: boot-app-gradle
  profiles:
    active: cloud
  devtools:
    livereload:
      port: 18090
      enabled: true

#log path
logs:
  absolute:
    path: /Users/mooney/hone/boot-app-gradle
  level:
    root: INFO
    com: DEBUG
  name: bootAppGradle
